package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MetaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMetaAllPropertiesEquals(Meta expected, Meta actual) {
        assertMetaAutoGeneratedPropertiesEquals(expected, actual);
        assertMetaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMetaAllUpdatablePropertiesEquals(Meta expected, Meta actual) {
        assertMetaUpdatableFieldsEquals(expected, actual);
        assertMetaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMetaAutoGeneratedPropertiesEquals(Meta expected, Meta actual) {
        assertThat(expected)
            .as("Verify Meta auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMetaUpdatableFieldsEquals(Meta expected, Meta actual) {
        assertThat(expected)
            .as("Verify Meta relevant properties")
            .satisfies(e -> assertThat(e.getValor()).as("check valor").isEqualTo(actual.getValor()))
            .satisfies(e -> assertThat(e.getArea()).as("check area").isEqualTo(actual.getArea()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMetaUpdatableRelationshipsEquals(Meta expected, Meta actual) {
        assertThat(expected)
            .as("Verify Meta relationships")
            .satisfies(e -> assertThat(e.getAluno()).as("check aluno").isEqualTo(actual.getAluno()));
    }
}
